---
archive:
  back_to_all_dates: Back to All Dates
  no_results: No results found.
  previous_page: Previous Page
  next_page: Next Page

forms:
  comment:
    name_placeholder: Name
    email_placeholder: Email
    url_placeholder: URL
    comment_placeholder: Your comment...

  subscribe:
    follow_link: Subscribe
    prompt: |
      <strong>Subscribe by email</strong>
      <span>Get email alerts about new posts. Unsubscribe anytime.</span>
    unfollow_link: <strong>Unsubscribe</strong>
    instructions: |
      <strong>Subscribe by email</strong>
      <span>Get email alerts about new posts. Unsubscribe anytime.</span>

read_more: Read more

pagination:
  first: First
  previous: Previous
  gap: …
  next: Next
  last: Last
