---
name: Omega
author: Posthaven
url: https//posthaven.com/
posts_per_page:
  include_in_settings: true
  default: 1
settings:
- id: header_bg_color
  label: Header Background
  type: color
- id: header_font_color
  label: Header Font Color
  type: color
